### ISSUE TITLE
是否可以直接引入dva并使用？

### ISSUE THREAD

**Issue by youxiaodao** [sxfad/react-admin#10]
你好，之前基于ant design pro做了几个页面，继续再做多页面的时候，发现您做的效果很棒，于是想把做好的页面迁移过来。
请问，是否可以直接引入dav并使用？
我尝试了：
`@connect(({ admin, loading }) => ({
  admin,
  loading: loading.effects['admin/list'],
}))
@config({
    path: '/system/BGroup/',
    ajax: true,
})
@Form.create()
class TableList extends PureComponent {
...

componentDidMount() {
        // console.log(this.dispatch,'hahahah')
        // const { dispatch } = this.props;
        dispatch({
            type: 'admin/list',
        });
    }

...
`
却不能运行，
报错内容：
`
TypeError: subscriber is undefined
dispatch
C:/Users/Lenovo/AppData/Local/Microsoft/TypeScript/3.6/node_modules/rxjs/internal/observable/pairs.js:51

  48 |     subscription = state.subscription,
  49 |     obj = state.obj;
  50 | 
> 51 | if (!subscriber.closed) {
     | ^  52 |   if (index < keys.length) {
  53 |     var key = keys[index];
  54 |     subscriber.next([key, obj[key]]);
`

**Comment by zkboys** [comment]
非常抱歉，这套架构只是用了ant design 作为组件，其他都是开源社区一些好的项目结合，与ant design pro 并没有关系。数据管理这块，是我们自己基于redux封装的，将redux写法封装成一个函数，同时没有改变redux写法，依然可以使用redux社区提供的一些中间件。

**Comment by zkboys** [comment]
系统中没有使用dva，不可直接使用，如果你的系统中页面不是很多，推荐迁移过来，改成react-admin的写法，这样系统相对统一，不会再引入一个dva增加系统复杂度。如果不好迁移，可以自己尝试把dva结合到react-admin中~

**Comment by youxiaodao** [comment]
非常感谢您的回复，页面不是太多，我就尝试迁移过来吧，
我是一个前端小白，并没有使用过redux。
如果可以提供一个完整的demo，让我可以照虎画猫，那就太感谢了

**Comment by zkboys** [comment]
参考代码：
pages/setting/index.jsx
models/settings.js
