### ISSUE TITLE
QueryBar的collapsed 属性支持自定义title吗？

### ISSUE THREAD

**Issue by goudanz** [sxfad/react-admin#100]
#96  比如我想显示成：‘展开/折叠’

![image](https://user-images.githubusercontent.com/23636449/130039518-dc2a4744-b795-4b15-8c33-c8ba3ffc6edc.png)

**Comment by goudanz** [comment]
比如我想显示成：‘展开/折叠’

**Comment by zkboys** [comment]
不支持，你可以参照源码自己实现一个QueryBar组件，源码在 [https://github.com/sxfad/react-admin-library/blob/master/src/components/query-bar/index.jsx](https://github.com/sxfad/react-admin-library/blob/master/src/components/query-bar/index.jsx)

**Comment by goudanz** [comment]
> 不支持，你可以参照源码自己实现一个QueryBar组件，源码在 https://github.com/sxfad/react-admin-library/blob/master/src/components/query-bar/index.jsx

好的，谢谢您
