### ISSUE TITLE
乾坤子应用

### ISSUE THREAD

**Issue by senjyouhara** [sxfad/react-admin#101]
我看src/index.js里有个乾坤子应用示例
```
export async function mount(props) {
  setMainApp(props.mainApp)
  render(props)
}
```
在子应用里我打印了下没有props.mainApp这个对象  问下这个props.mainApp对象是在哪里注入的

**Comment by zkboys** [comment]
这个是运行时，主应用提供的，如果不是嵌入到主应用运行，单独运行，是没有的。

**Comment by senjyouhara** [comment]
不是单独运行的  我是同时运行主应用和子应用  并将子应用嵌入到主应用运行的，那个对象还是没有

**Comment by zkboys** [comment]
是有问题，后期改动的时候，没注意微应用这块，已经修复 可以看一下有哪些改动：[乾坤子应用问题修复。](https://github.com/sxfad/react-admin/commit/1f8f25eeebeaf7635e1d28880d9cde47c50ab1a8)
另外，将@ra-lib/admin包升级到最新版本。0.0.67

**Comment by senjyouhara** [comment]
感谢修复  这次修复还有个bug  
api/system.js

```
    const props = {
      mainApp: {
        loginUser: loginUser,
        token: loginUser.token,
      },
    }
```
这里loginUser如果为null会引起报错

**Comment by zkboys** [comment]
这个也修复了，@ra-lib/admin里面，进行setLoginUser时，没有对参数做判断。

**Comment by senjyouhara** [comment]
还有个bug  model/index.js  
```
const result = createStoreByModels(models, {
    localStorage: storage.local,
    sessionStorage: storage.session,
    serialize: data => data,
    deserialize: data => data,
    onError: handleError,
    onSuccess: handleSuccess,
})
```
这里写入到localstorage的时候，localstorage的key会丢失userId，导致不能回写

**Comment by zkboys** [comment]
这个不算是bug，storage是根据用户id区分存储的，如果存储的时候，提供了userId，但是回写的时候，没有提供userId，自然不能回写。

**Comment by senjyouhara** [comment]
好吧  可能是我存储时机不对导致的。存储的时候没有userId  回写的时候有userId了引起的无法回写问题
