### ISSUE TITLE
无法直接点击顶层菜单就显示对应路由的页面。

### ISSUE THREAD

**Issue by goudanz** [sxfad/react-admin#104]
默认的系统管理中有：用户管理、角色管理、菜单管理等

然后我自己的业务有几个其他的菜单。然后这几个菜单想直接通过点击顶层菜单就访问对应路由的页面。但是貌似这样配置了。点击没啥效果；

这是我的菜单：
![image](https://user-images.githubusercontent.com/23636449/130745397-5c28749a-5ffb-44f3-a98c-ceca7f90f100.png)

这是菜单管理中的配置：
![image](https://user-images.githubusercontent.com/23636449/130745460-68eb9895-c6b8-4182-8e57-bd29bfd73d8d.png)

然后type都是”1“，

export const targetOptions = [
    {value: '', label: '项目内部窗口'},
    {value: '_self', label: '替换当前窗口'},
    {value: '_blank', label: '打开新窗口'},
];

target我写了_self和空都不行。

麻烦问下该怎么处理这个？

**Comment by zkboys** [comment]
```
{ key: 'test1', text: '一层内部菜单', icon: 'align-left', path: '/menus', order: 900 },
{ key: 'test2', text: '一层内嵌第三方', icon: 'align-left', url: 'https://baidu.com', target: '', order: 900 },
```

内部系统路由，使用path，如果是嵌入第三方，使用url 和 target。

**Comment by goudanz** [comment]
> ```
> { key: 'test1', text: '一层内部菜单', icon: 'align-left', path: '/menus', order: 900 },
> { key: 'test2', text: '一层内嵌第三方', icon: 'align-left', url: 'https://baidu.com', target: '', order: 900 },
> ```
> 
> 内部系统路由，使用path，如果是嵌入第三方，使用url 和 target。

好的，多谢大佬解答，我试试！多谢多谢！
