### ISSUE TITLE
如果在ajax请求回来前进行页面切换控制台会抛出错误

### ISSUE THREAD

**Issue by senjyouhara** [sxfad/react-admin#105]
如果在ajax请求回来前进行页面切换控制台会抛出错误
This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function

把@ra-lib/ajax/create-hooks.js里的
```
useState({
            loading: false,
            data: undefined,
            error: null,
        })
```
替换成
```
import { useSafeState } from "ahooks"
useSafeState({
        loading: false,
        data: undefined,
        error: null
      })
```
就没问题

**Comment by senjyouhara** [comment]
比较简单的重现步骤是用java写个接口
```
    @GetMapping("test")
    public String test() throws InterruptedException {
        Thread.sleep(1000 * 20);
        return "test";
    }
```
然后前端调用  调用后马上切换路由 控制台就会报异常

**Comment by zkboys** [comment]
前端代码是啥样的？

**Comment by senjyouhara** [comment]
前端代码只是修改了`pages/user/index.jsx`的list请求路径`user/queryUsersByPage`
然后修改了代理请求地址
访问user页面  然后切换role或者menu页面控制台就会报错
如果需要的话我上传下代码
https://github.com/senjyouhara/react-test

页面进去后从用户管理切换到别的页面就会发生报错

**Comment by zkboys** [comment]
是你的代码写的有问题， 不要再 ajax.instance.interceptors.response.use 的 onRejected 中进行错误处理，相关错误处理统一在src/handle-error.js中做。

如果非要在 ajax.instance.interceptors.response.use 的 onRejected 中 做处理，要区分是否是ajax取消
```js
error => {
    // Do something with response error
    if(error?.message?.canceled === true) return Promise.reject(error);

    console.log("err", error, error.response)
    let msg = error && typeof error.message === "string" ? error.message : errorCode["default"]
    if (error.response) {
      msg = errorCode[error.response.status] || error.response.data?.message || errorCode["default"]
    }

    return Promise.reject(msg)
  },
```

axois 会对 取消进行特殊处理，如果Promise.reject并不是取消，会继续后续promise.catch执行，就产生了你这个问题。

**Comment by senjyouhara** [comment]
好的  感谢解答  是我没仔细看代码
