### ISSUE TITLE
如果项目配置为子路径，路由为history模式，layout的tab将会失效

### ISSUE THREAD

**Issue by senjyouhara** [sxfad/react-admin#106]
比如 在src/config/index.js改为
`
export const BASE_NAME = getConfigValue("BASE_NAME", window.__POWERED_BY_QIANKUN__ ? `/${appPackage.name}` : "/admin")

//只列举了部分
CONFIG_HOC = {
  layoutType: LAYOUT_TYPE.SIDE_MENU,
    logoTheme: "dark",
    side: true,
    keepMenuOpen: true,
    sideTheme: "dark",
    searchMenu: true,
    header: false,
    tab: true,
    pageHeader: false,
    persistTab: true,
    tabSideToggle: true,
    tabHeaderExtra: true,
}
`
进行页面跳转后tab并不会添加  一直在首页  如果路由为hash模式则没这个问题

**Comment by zkboys** [comment]
升级一下 `@ra-lib/admin` 试试 `yarn add @ra-lib/admin`.

**Comment by senjyouhara** [comment]
可以了
