### ISSUE TITLE
麻烦请问下ajax.useDel、useGet、usePost这种方式怎么设置errorTip为接口返回的tip呢？

### ISSUE THREAD

**Issue by goudanz** [sxfad/react-admin#107]
目前我的代码是这么写的，

```
const [saving, saveSysDict] = props.ajax.usePost('/sys-dict', {successTip: '添加成功！',errorTip: '添加失败！'});
```

但是有时候，接口里会有一些其他的error提示。

比如:
![image](https://user-images.githubusercontent.com/23636449/133361299-91b4c7d1-66d4-49cf-bde8-ff0b77f7d2e9.png)

请问这种情况下```ajax.useDel```这种用法该如何定义error？

**Comment by zkboys** [comment]
几种方式，
一种是通过 saveSysDict.then 或者 saveSysDict.catch中自己实现提示
另一种是通过修改 handleError.js 或者 handleSuccess.js文件，根据后端约定，自动提示。
另一种是通过修改 ajax.js 中的相应拦截器
![image](https://user-images.githubusercontent.com/11864780/133362831-b2201976-a7e7-490b-b0d4-babe191ba310.png)

**Comment by goudanz** [comment]
> 几种方式，
> 一种是通过 saveSysDict.then 或者 saveSysDict.catch中自己实现提示
> 另一种是通过修改 handleError.js 或者 handleSuccess.js文件，根据后端约定，自动提示。
> 另一种是通过修改 ajax.js 中的相应拦截器
> ![image](https://user-images.githubusercontent.com/11864780/133362831-b2201976-a7e7-490b-b0d4-babe191ba310.png)

好的多谢多谢，我试试！

**Comment by goudanz** [comment]
再次谢谢您的解答；

不好意思，调了下发现之前我改过handleError.js 的代码，但因为我服务端这个接口在exception下返回了500，所以从```if (status >= 500) return serverErrorTip;```这句就直接跳出了。我应该返回400就可以走自定义message了；
