### ISSUE TITLE
createStoreByModels无法设置异步方法到state问题

### ISSUE THREAD

**Issue by senjyouhara** [sxfad/react-admin#109]
createStoreByModels里区分同步和异步的方法是通过这个语句来判断的
`Object.prototype.toString.call(value) === "[object AsyncFunction]"`  但是在项目的babel 会对async方法进行语法转换  引起这里异步判断失效  导致异步方法执行后设置state失效

**Comment by zkboys** [comment]
已解决，将 @ra-lib/admin 升级到 0.1.0 版本即可。

测试的时候浏览器兼容版本设置的比较高，babel没有对async函数进行转换。没有发现这个问题。
目前通过 函数字符串，转换后的一些特征字符做的判断。但是箭头函数方式无法判断，以后就用成员方法的方式吧。

只支持成员方法写法 `async getUser(id, state) {...},`
不支持成员属性=箭头函数的写法：`getUser: async (id, state) => {...},`
