### ISSUE TITLE
error Command failed with signal "SIGKILL".

### ISSUE THREAD

**Issue by jiangjkd** [sxfad/react-admin#11]
Starting the development server...

Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
error Command failed with signal "SIGKILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jiangjkd** [comment]
部署的时候出现这个吗？

**Comment by jiangjkd** [comment]
yarn start

**Comment by zkboys** [comment]
应该是你机器内存不足~

**Comment by Rinzin2018** [comment]
i am having same problem. is there any solution for that

**Comment by 78nbm78** [comment]
> i am having same problem. is there any solution for that

You need to increase your memory
