### ISSUE TITLE
有办法在modal的顶部添加操作按钮嘛？

### ISSUE THREAD

**Issue by goudanz** [sxfad/react-admin#110]
![image](https://user-images.githubusercontent.com/23636449/134794509-52c51f82-78c0-4938-b60f-efa9da99637e.png)

类似这种：

![image](https://user-images.githubusercontent.com/23636449/134794530-e9987916-eab6-4249-924b-08c71f064630.png)

**Comment by zkboys** [comment]
两种方式：
1. title可以直接返回一个jsx，但是与实际组件断层，不是很好整合逻辑。
```javascript
export default config({
    modal: {
        title: props => {
            return (
                <div
                    style={{
                        display: 'flex',
                        justifyContent: 'space-between',
                        paddingRight: 32,
                    }}>
                    <span>标题</span>
                    <Space>
                        <Button type="primary">操作1</Button>
                        <Button danger>操作2</Button>
                    </Space>
                </div>
            );
        },
        width: '70%',
        top: 50,
    },
})(function Edit(props) {
    ...
})
```

2. 不显示原弹框标题，自定义标题
```javascript
export default config({
    modal: {
        closable: false,
        width: '70%',
        top: 50,
    },
})(function Edit(props) {
...
    return (
        <ModalContent>
            <div
                style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    paddingBottom: 16,
                    marginBottom: 16,
                    borderBottom: '1px solid #f0f0f0',
                }}
            >
                <span>标题</span>

                <Space>
                    <Button type="primary">操作1</Button>
                    <Button danger>操作2</Button>
                    <CloseOutlined onClick={onCancel}/>
                </Space>
            </div>
        </ModalContent>
    );
})
```

**Comment by goudanz** [comment]
> 两种方式：
> 
> 1. title可以直接返回一个jsx，但是与实际组件断层，不是很好整合逻辑。
> 
> ```js
> export default config({
>     modal: {
>         title: props => {
>             return (
>                 <div
>                     style={{
>                         display: 'flex',
>                         justifyContent: 'space-between',
>                         paddingRight: 32,
>                     }}>
>                     <span>标题</span>
>                     <Space>
>                         <Button type="primary">操作1</Button>
>                         <Button danger>操作2</Button>
>                     </Space>
>                 </div>
>             );
>         },
>         width: '70%',
>         top: 50,
>     },
> })(function Edit(props) {
>     ...
> })
> ```
> 
> 1. 不显示原弹框标题，自定义标题
> 
> ```js
> export default config({
>     modal: {
>         closable: false,
>         width: '70%',
>         top: 50,
>     },
> })(function Edit(props) {
> ...
>     return (
>         <ModalContent>
>             <div
>                 style={{
>                     display: 'flex',
>                     justifyContent: 'space-between',
>                     alignItems: 'center',
>                     paddingBottom: 16,
>                     marginBottom: 16,
>                     borderBottom: '1px solid #f0f0f0',
>                 }}
>             >
>                 <span>标题</span>
> 
>                 <Space>
>                     <Button type="primary">操作1</Button>
>                     <Button danger>操作2</Button>
>                     <CloseOutlined onClick={onCancel}/>
>                 </Space>
>             </div>
>         </ModalContent>
>     );
> })
> ```

谢谢大佬！我赶紧试试

**Comment by goudanz** [comment]
搞定了！！！

![image](https://user-images.githubusercontent.com/23636449/134796465-c51e2bbc-a0df-4308-81d5-da48d1b6a79e.png)


万分感谢！
