### ISSUE TITLE
ModalContent如何控制top？

### ISSUE THREAD

**Issue by goudanz** [sxfad/react-admin#112]
大佬您好！不好意思又麻烦您了！

我写了一个Modal中的Modal，然后想和第一个Modal错位开！

### 现在是酱紫：
![image](https://user-images.githubusercontent.com/23636449/135019562-e967b9d5-5b46-43ba-9331-5753e6c48670.png)

### 我的做法是在这里控制，我写在modal里面和外面貌似都不行；
![image](https://user-images.githubusercontent.com/23636449/135019511-844fa7cb-fc8a-42e4-aa86-65854bd2a117.png)

### 我想要的效果：
![image](https://user-images.githubusercontent.com/23636449/135019640-6ecb7024-fe2d-474d-ac52-8aef09f0f113.png)

### 这个效果是我从：

ant-modal-content 的css中加了 top：140px
![image](https://user-images.githubusercontent.com/23636449/135019697-2e87e402-1590-4359-a6b5-2f6371ddfcce.png)

麻烦大佬看下，我是不是哪里写的不对？

**Comment by goudanz** [comment]
而且我看了ralib项目的
https://github.com/sxfad/react-admin-library/blob/master/src/hoc/modal-hoc/index.jsx#L26

 const {visible, onCancel, top = 100, style} = this.props;

他貌似使用外部传入的top决定的！

但不知道为啥没生效

**Comment by zkboys** [comment]
通过style
```javascript
export default config({
    modal: {
        style: {top: 150},
    },
})
````

**Comment by goudanz** [comment]
> 通过style
> 
> ```js
> export default config({
>     modal: {
>         style: {top: 150},
>     },
> })
> ```

搞定了！多谢大佬！
