### ISSUE TITLE
怎么添加文件上传组件 

### ISSUE THREAD

**Issue by jiangjkd** [sxfad/react-admin#12]
怎么添加文件上传组件 upload

**Comment by zkboys** [comment]
不属于架构范畴之内，请参考 ant design [Upload](https://ant-design.gitee.io/components/upload-cn/) 或者其他实现方式

**Comment by hellomolike** [comment]
大文件上传呢，比如有1g的文件要上传，antd的upload非常慢。有针对大文件的组件可以用么。
