### ISSUE TITLE
通过NavLink跳转的页面无法切换面包屑！

### ISSUE THREAD

**Issue by goudanz** [sxfad/react-admin#120]
## 问题：
我在一个页面使用NavLink to 的方式跳转页面，调到另一个页面后，无法切换面包屑！

## 过程：
这是第一个页面以及localStorage的值：
![image](https://user-images.githubusercontent.com/23636449/139174065-b0dac93a-d5e2-4b86-9344-e641b254c0de.png)

通过点击跳转功能进入另一个页面：
![image](https://user-images.githubusercontent.com/23636449/139174304-716c2ca2-eee1-49dc-8dbc-2f49ae92c5d7.png)

## 代码：
跳转的地方:
```
<NavLink styleName="operationLabel" to={`/issue/${item.id}`}>{item.title}</NavLink>
```

跳过去的地方：
```
useEffect(() => {
    (async () => {
        if(props.match.params.id) {
              // todo
        }
    })();
}, []);
```

## 我的方案:

我有想过读出来这个值，然后自己修改SelectedMenu 和topMenu，但是不知道从什么地方读取当前的菜单信息；
类似这种：
```
let currentLayout = JSON.parse(localStorage.getItem(`${userId}-layout`));
// 修改 SelectedMenu 和 topMenu
localStorage.setItem(`${userId}-layout`,JSON.stringify(currentLayout));
```

**Comment by zkboys** [comment]
可能是由于你的目标页面没有配置config高阶组件中没有配置title，或者不是菜单对应页面导致。
config高阶组件中可以修改面包屑：
```
// 自定义面包屑导航，默认基于选中菜单，false：不显示，[{icon, title, path}, ...]
breadcrumb,
// 基于菜单，追加面包屑导航
appendBreadcrumb,
```

**Comment by goudanz** [comment]
> breadcrumb

那每个页面都需要这么写吗？
![image](https://user-images.githubusercontent.com/23636449/141735662-3c5cb815-a8fa-4727-b0fd-bd41e63e9b98.png)


我现在的目标页面写的是：
```
export default config({path: '/issue/:id?'})((props) => {
```
要改成下面这样嘛？
```
export default config({path: '/issue/:id?', appendBreadcrumb :true})((props) => {
```

还是得这样子：

```
export default config(
    {
        path: '/issue/:id?', 
        title:{text:'需求'},
        breadcrumb:[{key:'issue',text:'需求'}]}
)((props) => {
```

但这样的话，那些动态的页面就没法弄了。因为没地方给写这个title和breadcrumb

**Comment by goudanz** [comment]
> 可能是由于你的目标页面没有配置config高阶组件中没有配置title，或者不是菜单对应页面导致。 config高阶组件中可以修改面包屑：
> 
> ```
> // 自定义面包屑导航，默认基于选中菜单，false：不显示，[{icon, title, path}, ...]
> breadcrumb,
> // 基于菜单，追加面包屑导航
> appendBreadcrumb,
> ```

我用了这种方式，可以切换了。但是还有动态的页面。是没有地方写title和breadcrumb的。

**Comment by zkboys** [comment]
1. 跳转的路由可以加title参数，比如： `props.history.push('/users?title=123')`
2. config高阶组件中，title可以写成函数
```
export default config({
    path: '/users',
    title: props =>  456,
})(function User(props) {...
```

**Comment by goudanz** [comment]
> 1. 跳转的路由可以加title参数，比如： `props.history.push('/users?title=123')`
> 2. config高阶组件中，title可以写成函数
> 
> ```
> export default config({
>     path: '/users',
>     title: props =>  456,
> })(function User(props) {...
> ```

谢谢大佬，我这么写，搞定了：

```
export default config({
    path: '/report_/:reportId',
    title: props => {
        return getUrlParams('title', window.location.search);
    },
    keepAlive: true,
})(props => {
```
