### ISSUE TITLE
麻烦问下，表格 columns 里的操作列按钮，可以使用 Permission 组件 来控制按钮的显示嘛？

### ISSUE THREAD

**Issue by goudanz** [sxfad/react-admin#123]
目前控制其他按钮我是这么弄得。
```
<Permission code='select' useDisabled={hasPermission()}>
    <Button onClick={()=>submit()}>查看</Button>
</Permission>
```

但是现在想对表格行内操作列的按钮进行控制，这个支持嘛？

![image](https://user-images.githubusercontent.com/23636449/144384359-3717c57c-fb6a-48e4-b649-f3688a639f53.png)
![image](https://user-images.githubusercontent.com/23636449/144384909-da0a14fa-b949-4a44-b9ac-cbae3d37fe14.png)

**Comment by zkboys** [comment]
不支持，如果操作列需要权限控制，可以使用hasPermisson('SOME_CODE')函数，通过处理items实现：

**Comment by zkboys** [comment]
不支持，如果操作列需要权限控制，可以使用hasPermisson('SOME_CODE')函数，通过处理items实现：
```js
const items = [
    {
        label: '查看',
        onClick: () => setRecord({...record, isDetail: true}) || setVisible(true),
        disabled: hasPermission('SOME_CODE'), // disabled范式
    },
    {
        label: '修改',
        onClick: () => setRecord(record) || setVisible(true),
    },
    // 没权限直接不显示
    hasPermission('SOME_CODE') && {
        label: '删除',
        color: 'red',
        confirm: {
            title: `您确定删除「${name}」吗？`,
            onConfirm: () => handleDelete(id),
        },
    },
].filter(Boolean);
```

**Comment by goudanz** [comment]
> 不支持，如果操作列需要权限控制，可以使用hasPermisson('SOME_CODE')函数，通过处理items实现：
> 
> ```js
> const items = [
>     {
>         label: '查看',
>         onClick: () => setRecord({...record, isDetail: true}) || setVisible(true),
>         disabled: hasPermission('SOME_CODE'), // disabled范式
>     },
>     {
>         label: '修改',
>         onClick: () => setRecord(record) || setVisible(true),
>     },
>     // 没权限直接不显示
>     hasPermission('SOME_CODE') && {
>         label: '删除',
>         color: 'red',
>         confirm: {
>             title: `您确定删除「${name}」吗？`,
>             onConfirm: () => handleDelete(id),
>         },
>     },
> ].filter(Boolean);
> ```

好的，明白了。多谢您的解释。麻烦您了~
