### ISSUE TITLE
ajax.js 响应拦截不生效 需要修改什么地方吗

### ISSUE THREAD

**Issue by Mrwuchuan** [sxfad/react-admin#125]
// 响应拦截
ajax.instance.interceptors.response.use(res => {
    // Do something before response

    // 后端自定义失败，前端直接抛出，走handleError逻辑
    if (typeof res.data === 'object' && 'code' in res && res.code !== '0000') return Promise.reject(res.data);
    console.log('res => ', res)
    return res;
}, error => {
    // Do something with response error
    return Promise.reject(error);
});

**Comment by Mrwuchuan** [comment]
我明白你的意思， 现在的问题是 我如果设置了ajax.instance.interceptors.request.use 请求拦截那么响应拦截就会失效 里面的代码根本就没有执行， 把请求拦截注释掉响应拦截才会生效

**Comment by Mrwuchuan** [comment]
> 这个要根据你们自己的后端返回的res数据结构进行判断

我明白你的意思， 现在的问题是 我如果设置了ajax.instance.interceptors.request.use 请求拦截那么响应拦截就会失效 里面的代码根本就没有执行， 把请求拦截注释掉响应拦截才会生效

**Comment by zkboys** [comment]
是不是请求拦截里面的代码有报错呢？

**Comment by Mrwuchuan** [comment]
> 是不是请求拦截里面的代码有报错呢？
没有报错输出   上面的那段代码没有执行

**Comment by Mrwuchuan** [comment]
> 是不是请求拦截里面的代码有报错呢？
我重新clone 了最新代码 没有这个问题 axios 0.21.2版本有这个问题
