### ISSUE TITLE
代码生成的页面被删除了吗？

### ISSUE THREAD

**Issue by youxiaodao** [sxfad/react-admin#14]
在最新拉取的代码中。没有代码生成相关的页面，
请问是剔除了吗？

**Comment by zkboys** [comment]
项目做了一些调整，代码生成相关页面在Tag：1.0.0分支。https://github.com/sxfad/react-admin/tree/1.0.0

**Comment by zkboys** [comment]
给您带来不便，抱歉~

**Comment by youxiaodao** [comment]
了解了，感谢您的答复~
