### ISSUE TITLE
动态路由，path一样 传参不同  菜单选中的问题

### ISSUE THREAD

**Issue by fengxin5571** [sxfad/react-admin#141]
动态路由，path一样 传参不同  菜单选中的怎么弄

**Comment by zkboys** [comment]
```

export default config({
    path: '/users',
    selectedMenuPath: '/users/:id',
})(function User(props) {...})
```

**Comment by fengxin5571** [comment]
> ```
> 
> export default config({
>     path: '/users',
>     selectedMenuPath: '/users/:id',
> })(function User(props) {...})
> ```

我是试了 可我路由地址是一样的 selectedMenuPath 只有刷新才有用

**Comment by zkboys** [comment]
```
// 菜单配置
{id: 2, parentId: 1, title: '用户管理', path: '/users/:id', order: 900, type: 1}

// 页面路由paht配置
export default config({
    path: '/users/:userId',
    selectedMenuPath: '/users/:id',
})(function User(props) {...})

// 其他页面跳转
<div onClick={() => props.history.push('/users/123')}>用户详情</div>
```

**Comment by fengxin5571** [comment]
> selectedMenuPath: '/users/:id',

好的 谢谢啦 我去试试去

**Comment by fengxin5571** [comment]
> ```
> // 菜单配置
> {id: 2, parentId: 1, title: '用户管理', path: '/users/:id', order: 900, type: 1}
> 
> // 页面路由paht配置
> export default config({
>     path: '/users/:userId',
>     selectedMenuPath: '/users/:id',
> })(function User(props) {...})
> 
> // 其他页面跳转
> <div onClick={() => props.history.push('/users/123')}>用户详情</div>
> ```

左侧菜单要是按照你这种改法 该怎么修改呢 求赐教

**Comment by zakihong** [comment]
@config({
  path: '/flows/:id',
  selectedMenuPath: '/flows',
  side: true,
  title: { text: '详情' },
})这样在刷新的时候选不中flows菜单，求赐教，怎么解决呀
