### ISSUE TITLE
ra-lib不再维护了么，没有仓库了

### ISSUE THREAD

**Issue by bj1116** [sxfad/react-admin#148]
https://sxfad.github.io/ra-lib/

**Comment by zkboys** [comment]
这个还维护，库涉及到一点公司内部东西，删除了。

**Comment by bj1116** [comment]
react-admin 这个还继续维护么，比较久没更新了，这边一直用，非常感谢！
里面 ra-lib是否可以剥离出去，或者重新发布一个，大家一起维护下。

**Comment by bj1116** [comment]
ok

**Comment by MoonS11** [comment]
有没有ra-Lib得文档
