### ISSUE TITLE
单独定义action 和 reducer如何使用？

### ISSUE THREAD

**Issue by zjlzlr** [sxfad/react-admin#17]
单独定义action 和 reducer,这个可以和现有的redux结合起来使用吗？有demo吧？

**Comment by zkboys** [comment]
[https://open.vbill.cn/react-admin/MODEL.html](https://open.vbill.cn/react-admin/MODEL.html) 这里有文档，没有尝试过跟现有以存在的redux结合使用，你可以尝试一下~

**Comment by zjlzlr** [comment]
嗯，试了下，单独创建一套action,reducer,通过store实例调用可以
