### ISSUE TITLE
react-admin用户列表如何进入edit详情界面呢？

### ISSUE THREAD

**Issue by damen-tao** [sxfad/react-admin#19]
大神，请问下从用户列表如何进入edit详情界面,我在Table组件上加上onRow对象新增toEdit（record）方法，在此方法中我该如何实现路由跳转进入到edit界面

**Comment by zkboys** [comment]
可以通过 react-router 相关方法跳转到详情页
@config({router: true})
...
this.props.history.push('path/to/edit')
