### ISSUE TITLE
yarn下载资源发生500错误

### ISSUE THREAD

**Issue by flyfreely2014** [sxfad/react-admin#2]
使用yarn安装依赖时发生HTTP 500错误，国内网络，国外代理均出现此现象
[yarn-error.log](https://github.com/sxfad/react-admin/files/2882756/yarn-error.log)
![wx20190220-102458](https://user-images.githubusercontent.com/7914779/53061834-d9609f80-34f9-11e9-901a-1609c5315471.png)

**Comment by zkboys** [comment]
解决了，重新pull一下试试~
