### ISSUE TITLE
菜单怎么设置隐藏

### ISSUE THREAD

**Issue by xiaokeng** [sxfad/react-admin#22]
目前不在menus.js里配置，可实现不显示。但通过上边tabs切换已打开的页面，没有在menus.js里配置的页面，需要点击2次才能切换

**Comment by zkboys** [comment]
有两种方式实现不显示左侧菜单：
1. src/models/settings.js 中设置布局方式为TOP_MENU

**Comment by xiaokeng** [comment]
不是不显示整个左菜单，是不显示左菜单中的某一tab

**Comment by zkboys** [comment]
目前不支持，tab是基于url地址，只要url地址不同，就会开启一个新的tab
