### ISSUE TITLE
如何打包发布

### ISSUE THREAD

**Issue by damen-tao** [sxfad/react-admin#23]
您好，请问如何打包发布，通过build指令打包后 总是找不到login页面，这个是什么原因呢？

**Comment by zkboys** [comment]
部署时，如果使用ng，参考项目中的nginx-config中的配置，如果使用其他web容器，将404页面重定向到index.html

**Comment by damen-tao** [comment]
我按照这个配置来跑不起来，通过IIS发布默认跳到login路由,

您有空帮我看看吗&nbsp;，我可以发源码给你





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ShubinWang"<notifications@github.com&gt;; 
发送时间: 2020年3月26日(星期四) 晚上7:45
收件人: "sxfad/react-admin"<react-admin@noreply.github.com&gt;; 
抄送: "呆萌-锋"<790453973@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sxfad/react-admin] 如何打包发布 (#23)





 
部署时，如果使用ng，参考项目中的nginx-config中的配置，如果使用其他web容器，将404页面重定向到index.html

**Comment by damen-tao** [comment]
刚刚学这个，或者教下我如何配置一下nginx-config, 我在IIS本地部署路径指向build就报找不到login
![image](https://user-images.githubusercontent.com/60916438/77644146-9219cd80-6f9b-11ea-883d-5ceed73d1aca.png)

**Comment by zkboys** [comment]
可以网上查一下单页面应用部署方式
