### ISSUE TITLE
跨域 问题

### ISSUE THREAD

**Issue by damen-tao** [sxfad/react-admin#24]
问下这边我iis发布会，总是无法跨域访问后台接口，前端代码中需要哪里做配置吗

**Comment by zkboys** [comment]
部署的时候，需要web服务器对接口进行反向代理。

**Comment by damen-tao** [comment]
嗯 这边问题我都解决了
 &nbsp;
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"ShubinWang"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年3月28日(星期六) 晚上6:15
 收件人:&nbsp;"sxfad/react-admin"<react-admin@noreply.github.com&gt;;
 抄送:&nbsp;"呆萌-锋"<790453973@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [sxfad/react-admin] 跨域 问题 (#24)

 

 

 
部署的时候，需要web服务器对接口进行反向代理。
