### ISSUE TITLE
二级页面刷新问题

### ISSUE THREAD

**Issue by damen-tao** [sxfad/react-admin#25]
当打开为二级页面时，刷新浏览器为什么路由会作为一个接口调用呢？

http://localhost:4001/house/_/edit/48

Request Method: GET
Status Code: 200 OK

图片如下
[https://sm.ms/image/hfnz3PkuA7tXMNB](url)

**Comment by zkboys** [comment]
这个4001端口，是yarn start启动的吗？src/setupProxy.js 代理是怎么配置的？

**Comment by zkboys** [comment]
二级页面能否正常访问？浏览器的这个Network会显示所有类型的请求，包括页面请求，你这个截图也许是Doc类型的请求，并不是XHR请求。
![image](https://user-images.githubusercontent.com/11864780/77820968-4002b480-7121-11ea-925f-bdd7dbeb05d8.png)

**Comment by damen-tao** [comment]
也解决了 只是打包的问题，导致路由跳转的时候出现homepage:'.'加了一个点导致路由跳转向上一级访问导致错误




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ShubinWang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月28日(星期六) 晚上6:23
收件人:&nbsp;"sxfad/react-admin"<react-admin@noreply.github.com&gt;;
抄送:&nbsp;"呆萌-锋"<790453973@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sxfad/react-admin] 二级页面刷新问题 (#25)





 
二级页面能否正常访问？浏览器的这个Network会显示所有类型的请求，包括页面请求，你这个截图也许是Doc类型的请求，并不是XHR请求。
