### ISSUE TITLE
每个页面接口请求都会请求两次

### ISSUE THREAD

**Issue by damen-tao** [sxfad/react-admin#26]
您好 我想咨询一下为什么每个页面请求都会请求两次？我请求的时候带参数的，但是我点开页面的时候一个同一个接口请求两次一个带参数，一个不带参数？ 这是什么原因造成的，是需要哪里配置什么吗？

图片如下
不带参数：https://sm.ms/image/5THWdXONRahESYg
带参数：https://sm.ms/image/1mSI9sXcLOZJRib

**Comment by zkboys** [comment]
第一个请求是OPTIONS请求，由于跨域引起的，从你的请求地址来开，应该是ajax直接连接了后端，而不是使用代理。最好是配置代理，不要直接请求后端，具体如何配置，文档有说明。
