### ISSUE TITLE
编辑表格组件不能正常显示

### ISSUE THREAD

**Issue by lmr520** [sxfad/react-admin#28]
<tableEditable
                                    loading={true}
                                    columns={columns}
                                    dataSource={this.state.dataT}
                                    rowKey="id"
                                    pagination={false}
                                />

dom:<tableeditable columns="[object Object],[object Object],[object Object],[object Object]" datasource="[object Object]" rowkey="id"></tableeditable>

**Comment by zkboys** [comment]
能描述的详细一些，或者有截图吗？

**Comment by lmr520** [comment]
![Uploading image.png…]()

**Comment by lmr520** [comment]
大佬要不你给一个可编辑表格组件的使用例子,我这里无法使用

**Comment by zkboys** [comment]
不好意思，最近工作有些忙，昨天你上传的图片打不开。可以尝试修改样式，或者参考ant design官网可编辑表格示例：https://3x.ant.design/components/table-cn/#components-table-demo-edit-cell
