### ISSUE TITLE
QueryItem组件的extra属性，只能加一个按钮控件吗？

### ISSUE THREAD

**Issue by motolorar** [sxfad/react-admin#29]
<QueryItem
                        collapsed={collapsed}
                        loadOptions={this.fetchOptions}
                        items={this.queryItems}
                        onSubmit={params => this.setState({ params }, this.handleSearch)}
                        extra={\<Button type="primary" icon="user-add" onClick={this.handleAdd}>添加客户\</Button>,
                            \<Button type="primary" icon="user-del" onClick={this.handleBatchDel}>批量删除客户\</Button>
                        }
                    />
这个代码块都是显示“批量删除客户”按钮，不显示前面一个。

**Comment by zkboys** [comment]
jsx 必须只能有一个跟节点，你两个Button并列就不行了，外面套个div，或者返回一个数据组，或者使用Fragment等
```react
<QueryItem
    collapsed={collapsed}
    loadOptions={this.fetchOptions}
    items={this.queryItems}
    onSubmit={params => this.setState({ params }, this.handleSearch)}
    extra={
        <div>
            <Button type="primary" icon="user-add" onClick={this.handleAdd}>添加客户</Button>
            <Button type="primary" icon="user-del" onClick={this.handleBatchDel}>批量删除客户</Button>
        </div>
    }
/>
```

**Comment by motolorar** [comment]
问题解决了，谢谢！
