### ISSUE TITLE
Mock的使用

### ISSUE THREAD

**Issue by zhaoxunyong** [sxfad/react-admin#3]
请问一下，Mock是怎么使用的？文档中写的没怎么看懂。比如说我需要添加一个页面，对应的path为/user/userlist，我想mock一下对应的json数据。

**Comment by zkboys** [comment]
mock功能能是提供假接口，跟页面的path没有任何关系，mock接口定义好之后，使用上和真实后端接口没有区别。

## 编写mock数据：
mock在src/mock目录下编写，可以参考 mock-user-center.js；

## 使用mock接口：
比如mock-user-center.js中有个 'get /mock/user-center': (config) => {.....}
在组件中直接通过get方法，url为`/mock/user-center`调用即可：
```js
this.props.ajax
    .get('/mock/user-center', {...params, pageNum, pageSize})
    .then(res => {
        console.log(res);
        if (res) {
            const {list: dataSource, total} = res;
            this.setState({
                dataSource,
                total,
            });
        }
    })
    .finally(() => this.setState({loading: false}));
```
注意：mock接口的url约定以`/mock/`开头，或在src/mock/url-config.js中配置，this.props.ajax会根据约定，区分调用mock接口，还是后端真实接口。

系统中只是提供了一个简单的mock功能，如果有后端接口了，需要修改url为后端真实接口，如果忘记修改，线上就404了，一般团队都会有一个mock平台，通过平台切换，前端并不需要在修改url。mock平台将mock数据从前后端中抽离出去单独维护，会使前后端开发协作更无缝、更友好。我司还未大量使用mock平台，有兴趣可以google一下~
