### ISSUE TITLE
之前的旧版本  ,出现升级提示要怎么操作

### ISSUE THREAD

**Issue by xiaokeng** [sxfad/react-admin#30]
`Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
`

**Comment by zkboys** [comment]
碰过这个问题，有点久远了，好像是升级postcss 相关的包解决的，这提示不解决问题应该也不大。

**Comment by zkboys** [comment]
执行 yarn upgrade postcss-preset-env 可以解决
