### ISSUE TITLE
npm install 后使用antd 的Tabs 样式错乱

### ISSUE THREAD

**Issue by canoelu** [sxfad/react-admin#33]
使用yarn 安装包后，yarn start 没有问题
但是使用npm install 安装的包，antd的Tabs样式错乱。
望解答下

**Comment by zkboys** [comment]
antd版本引起的，通过npm安装，会使antd依赖的rc-tabs版本为11，样式会乱，具体原因未知
解决办法：固定antd版本 npm install antd@4.2.4
