### ISSUE TITLE
大佬发现弹出窗Tabs 出来<>

### ISSUE THREAD

**Issue by yuchengx** [sxfad/react-admin#39]
![1593099778(1)](https://user-images.githubusercontent.com/32560819/85752053-a9548c80-b73d-11ea-8686-06cfe22af6d2.jpg)弹出用tags出来

**Comment by zkboys** [comment]
这个问题由于antd引起的。把antd卸载了，`yarn remove antd`  再安装：`yarn add antd@4.2.4`

**Comment by yuchengx** [comment]
膜拜前端大佬

**Comment by yuchengx** [comment]
可以把那个改颜色的弄出来吗

**Comment by yuchengx** [comment]
主颜色

**Comment by zkboys** [comment]
比较花哨的东西，中后台管理系统，一般公司内部使用，感觉没什么用，给去掉了，想加可以参考v3分支，里面有。目前分支可以通过修改theme.js里面的primay-color改变主题颜色，但是需要重新构建，不支持用户自己选择
