### ISSUE TITLE
ajax Network Error

### ISSUE THREAD

**Issue by zhaoxunyong** [sxfad/react-admin#4]
请问一下，我新增了一个页面，远端服务器模拟了数据，我修改了setupProxy.js：

![image](https://user-images.githubusercontent.com/8733266/54095586-090d1400-43e3-11e9-8bee-3b23e6a8b78e.png)

mock url为：http://yapi.aeasycredit.net/mock/32/api/loanAccountList

![image](https://user-images.githubusercontent.com/8733266/54095646-4b365580-43e3-11e9-8d7a-7209dcf4fa76.png)

但console中报这个错误，是不是哪个地方需要配置权限？

![image](https://user-images.githubusercontent.com/8733266/54095547-dfec8380-43e2-11e9-8926-f857d6a7c433.png)

谢谢~

**Comment by zkboys** [comment]
url不要以api/开头，直接以/开头，ajax封装统一添加了api/前缀

**Comment by zhaoxunyong** [comment]
我再试试，谢谢

**Comment by zhaoxunyong** [comment]
报这个错误：OPTIONS http://localhost/users/sign_in net::ERR_CONNECTION_REFUSED，好像重新定向到了登录页面，这个是不是要设置权限？

**Comment by zkboys** [comment]
> 报这个错误：OPTIONS http://localhost/users/sign_in net::ERR_CONNECTION_REFUSED，好像重新定向到了登录页面，这个是不是要设置权限？

最近在忙别的事情，不知道你这个解决了没有？
