### ISSUE TITLE
不支持浏览器前缀自动补全

### ISSUE THREAD

**Issue by samsonCao** [sxfad/react-admin#40]
书写的less文件样式，不支持浏览器前缀自动补全，如
下面代码为less文件
`.sideContent {
  flex: 1;
}`

下面代码为编译后的css
`.sideContent {
  flex: 1;
}`
没有自动添加浏览器前缀-web-kit.....

**Comment by zkboys** [comment]
可以通过调整 package.json 中的 browserslist 配置进行支持。如果是中后台管理系统，公司内部使用不必添加前缀，保证兼容常用现代浏览器即可。
