### ISSUE TITLE
左侧导航点击后出现404错误页面

### ISSUE THREAD

**Issue by rennner** [sxfad/react-admin#43]
1、yarn  & yarn start  报错
./src/pages/page-routes.js
Module not found: You attempted to import /Users/wangshubin/workspace/suixingpay/application-dependency/admin-front/src/pages/home/index.jsx which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
2、手动修改./src/pages/page-routes.js 进入页面，单点击左侧导航菜单，所有路由按钮点击均是404错误页面

**Comment by rennner** [comment]
试了一linux可以运行。win下需要做什么设置吗？

**Comment by zkboys** [comment]
windows平台有兼容性问题，已解决，方法如下：
[https://github.com/sxfad/react-admin/commit/5d8a42a6f3afad5f7ef0561c0307c13fb6aa047e](https://github.com/sxfad/react-admin/commit/5d8a42a6f3afad5f7ef0561c0307c13fb6aa047e)
