### ISSUE TITLE
请教：为什么打包到服务器会自动跳404路由

### ISSUE THREAD

**Issue by chieway** [sxfad/react-admin#51]
我在package.ison添加了"homepage": ".",然后yarn build，打包到线上会显示404组件

**Comment by zkboys** [comment]
服务器用的是啥？ng？

**Comment by chieway** [comment]
用的apache

**Comment by chieway** [comment]
在publice目录下创建了.htaccess文件解决了
Options -MultiViews
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.html [QSA,L]
