### ISSUE TITLE
http-proxy-middleware 问题

### ISSUE THREAD

**Issue by marquisXuan** [sxfad/react-admin#53]
**http-proxy-middleware 版本**： ^1.0.6 (自己 npm install --save-dev http-proxy-middleware添加的)

**setupProxy.js配置**

```js
const {createProxyMiddleware} = require('http-proxy-middleware')

const prefix = process.env.AJAX_PREFIX || '/api/fv-admin'
console.info('代理相关', prefix)

module.exports = function (app) {
    app.use(createProxyMiddleware(
        prefix,
        {
            target: 'http://localhost:8080/',
            pathRewrite: {
                '/api': '', // 如果后端接口无前缀，可以通过这种方式去掉
            },
            changeOrigin: true,
            secure: false, // 是否验证证书
            ws: true, // 启用websocket
        },
    ))
}

```

**ajax请求**

```js
let {pageNum, pageSize} = this.state
this.props.ajax
    .get(`/goods/sys-goods/list?currentPage=${pageNum}&offset=${pageSize}`)
    .then(res => {
        console.log(res)
    })
```

**项目启动控制台**

![image](https://user-images.githubusercontent.com/22328979/102928136-31d89d80-44d3-11eb-9e06-5dfba389673b.png)

**实际结果**

![image](https://user-images.githubusercontent.com/22328979/102928071-14a3cf00-44d3-11eb-8097-ed8238371588.png)
![image](https://user-images.githubusercontent.com/22328979/102928104-1d94a080-44d3-11eb-8f1d-b8aa353640c6.png)

**疑问**

代理配置没生效还是怎么回事。。。前端小白，不知如何下手。不用react-admin的时候，这样的配置可以代理成功。react-admin里的东西太多了，还没学完，碰到了这么一个问题，一直没解决。。。还请指点一下

**Comment by zkboys** [comment]
这个不像是代理问题，不知用代理，直接访问后端，可以访问的到吗？

**Comment by marquisXuan** [comment]
@zkboys 直接在浏览器地址栏上访问是可以正常出数据的。

**Comment by marquisXuan** [comment]
@zkboys 如果直接在react-admin里访问后端接口，就会报跨域的错误。虽然我可以用nginx来解决这个跨域问题，但是我不知道为什么这个**代理配置没起作用**。。因为在别的项目中有用过1.0.5版本的http-proxy-middleware.也是这样配置的，就解决了跨域的问题。。。
![image](https://user-images.githubusercontent.com/22328979/103029728-63b23880-4595-11eb-8f73-5c73b69382e7.png)

![image](https://user-images.githubusercontent.com/22328979/103029170-2ac59400-4594-11eb-8934-8e9e4907d4fb.png)
![image](https://user-images.githubusercontent.com/22328979/103029197-387b1980-4594-11eb-92f1-b7ca7d855951.png)

**Comment by marquisXuan** [comment]
502通常指网关错误。我直接把Network里的路径放到地址栏里，发现是nginx做的服务器，不知道这是react-admin框架里管理的还是什么。我先把本机nginx关掉再看看。
![image](https://user-images.githubusercontent.com/22328979/103031005-efc55f80-4597-11eb-94bd-50f035d7a3a5.png)

**Comment by marquisXuan** [comment]
# Closed
问题解决了。果真不是代理的问题。我的nginx一直在代理8080端口。导致失败。。。。好大一个乌龙。
@zkboys 谢谢～辛苦了
