### ISSUE TITLE
FormElement 数据回显问题

### ISSUE THREAD

**Issue by marquisXuan** [sxfad/react-admin#54]
### 描述：

服务端返回数据为 number 类型的 0 
页面中FormElement的type为select。其中0假如对应实物商品，期望展示实物商品，而非 0 

### 代码截图

<img width="885" alt="image" src="https://user-images.githubusercontent.com/22328979/103147165-624b6080-478d-11eb-975e-6586e2611636.png">

<img width="762" alt="image" src="https://user-images.githubusercontent.com/22328979/103147168-70997c80-478d-11eb-8aea-61e0d5fd5a6a.png">

![image](https://user-images.githubusercontent.com/22328979/103147174-9b83d080-478d-11eb-8e61-8deb6de1912e.png)

实际上，我想要达到这样的效果。服务端返回0，页面渲染出0对就的中文意义。咱们的文档中也没有类似的例子[哭]又不知道怎么搞了。。。

![image](https://user-images.githubusercontent.com/22328979/103147179-a9395600-478d-11eb-87e8-ef4949043653.png)

最初我以为是数据类型不匹配导致无法正确渲染。所以将value:'0' 改为了 value:0。但是还是没有达到想到的效果。在**codesandbox**中用原生的antd的Select组件写了一下。发现是可以的。
![image](https://user-images.githubusercontent.com/22328979/103147322-303afe00-478f-11eb-8f52-97bac65d8d70.png)

好像不太会用 react-admin这个框架[捂脸]
如果使用Form.Item就可以正常了。。。
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/22328979/103147399-8b6cf080-478f-11eb-8b22-9b5e8142f96d.png">
![image](https://user-images.githubusercontent.com/22328979/103147401-90ca3b00-478f-11eb-99f8-59899c56074d.png)

**Comment by marquisXuan** [comment]
请问一下，是不是我的姿势不太对。。。。。。。

**Comment by zkboys** [comment]
后端返回的数据改成string类型，options的value都用string类型试试

**Comment by marquisXuan** [comment]
> 后端返回的数据改成string类型，options的value都用string类型试试

谢谢～
String渲染成功了。但是这样就要把所有的服务器返回值类型改一下了。。不应该吧[捂脸]，所以目前我还是使用的Form.Item来处理
