### ISSUE TITLE
您好，网站登录会话过期的时候，怎么更加友好的处理

### ISSUE THREAD

**Issue by SevenZLL** [sxfad/react-admin#57]
1.我在发送请求的时候，根据返回的状态码判断token（会话）是否过期，直接跳转到登录页 
![e2f8b55bfad805a6e159e0073d291cd1](https://user-images.githubusercontent.com/28469652/104434653-6cab8e00-55c6-11eb-95f9-ed63be5d33c6.jpg)

，再次登录的时候，就会出现第一个页签就是URL 就是‘/login’ ，却保留了原来保持打开的页签。一共两个标签页，而不是保持原来之前打开多个菜单页签的状态了。经查验loacalstorage 中就保留两个页签，其中一个是登录页（空白页签）

2.本地的loacalstorage是怎么写进去的，我找好久的代码，其中[object Object]-system,[object Object]-menu,[object Object]-side 不知道从那个代码片段写进去的，超时的时候，我想通过这改变这个能改善上诉的问题吗，再次登录保留原来打开的页签，完全退出系统的时候，再次登录不保留当时打开的页签或者也可以保留原来页签。
![8b5e7f851e2d6e2bc6d311c85af7b9bf](https://user-images.githubusercontent.com/28469652/104435619-8bf6eb00-55c7-11eb-8412-9f8c4c353ec0.jpg)

**Comment by zkboys** [comment]
你查一下登录成功之后，时候正确设置了用户，应该是setLoginUser方法，必要字段id和name，id是否为数字或者字符串？

**Comment by SevenZLL** [comment]
**代码截图 setLoginUser 方法** 
用户信息一开始我就赋值进去了
![8cf15ec26a33705ac3255e0636710f84](https://user-images.githubusercontent.com/28469652/104532628-9ce94000-564b-11eb-82c4-491e966a8a7b.jpg)

**Comment by SevenZLL** [comment]
我重新设置了用户参数
还是出现这个问题
**正常的退出和登录都能保持一致**
![image](https://user-images.githubusercontent.com/28469652/104533976-5c3ef600-564e-11eb-90a0-76785b47f64e.png)

**删除redis 中存放的token ，刷新界面之后再次登录**
![image](https://user-images.githubusercontent.com/28469652/104534083-8ee8ee80-564e-11eb-88b0-3f4e42b5e70c.png)

**Comment by zkboys** [comment]
App.js 初始化state loading 改为true， 然后把 local Storage 都请了，重新试试
![image](https://user-images.githubusercontent.com/11864780/104553078-f9148a00-5674-11eb-8146-53805035ea9e.png)

**Comment by SevenZLL** [comment]
已经可以了，谢谢解答和指导
