### ISSUE TITLE
npm run start 报错

### ISSUE THREAD

**Issue by Junrui-L** [sxfad/react-admin#58]
Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 000000000014D9E0npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! react-adminv4@4.0.0 start: `node scripts/start.js`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the react-adminv4@4.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2021-01-15T08_01_20_092Z-debug.log

**Comment by mogocat** [comment]
请发出log和版本号等信息
Please post your log content and versions info

**Comment by changchengyan** [comment]
我知道啥原因，你 把package.jsonz中 修改成这样
```
 "scripts": {
        "start": "node scripts/start.js",
        xxx,
        xxx
}
```
