### ISSUE TITLE
代码生成工具获取数据库表名返回错误

### ISSUE THREAD

**Issue by liaoyongxiong** [sxfad/react-admin#6]
提供代码生成工具是本脚手架跟其他同类脚手架比一个很大的亮点，但在生成界面点击“获取数据库表名“时，返回了”获取数据库表失败“，如下图：
<img width="1114" alt="屏幕快照 2019-04-09 12 09 40" src="https://user-images.githubusercontent.com/9619081/55772840-a92c8a80-5ac0-11e9-9987-1cce582e8023.png">

环境：Mac，mysql+react-admin在同一主机运行。
另外，代码生成工具这部分的使用说明可以写详细点，感谢。

**Comment by zkboys** [comment]
具体错误通过 Network标签查看一下~排除是否是配置错误。
比如这样的：
![image](https://user-images.githubusercontent.com/11864780/55782213-5feb3380-5ade-11e9-862b-9ff122ef623a.png)

**Comment by liaoyongxiong** [comment]
此问题是数据库版本太高（mysql 8.0.15），node.js不支持此版本的默认认证方式。将数据库回退到5.7后可以了。
