### ISSUE TITLE
ModalContent组件设置width无效

### ISSUE THREAD

**Issue by holiy930561** [sxfad/react-admin#60]
<ModalContent
                bodyStyle={{width:'1000px'}}
                style={{width:'1000px'}}
                loading={loading}
                okText="保存"
                cancelText="重置"
                onOk={() => this.okFn()}
                onCancel={() => this.cancelFn()}
            >
            </ModalContent>
![微信图片_20210118162027](https://user-images.githubusercontent.com/63273780/104889606-6728bc00-59a9-11eb-8128-6733ba1b0d3a.png)
![微信图片_20210118162035](https://user-images.githubusercontent.com/63273780/104889612-698b1600-59a9-11eb-896d-4d0ab3c75cd7.png)

**Comment by holiy930561** [comment]
一直都是800px

**Comment by zkboys** [comment]
在高阶组件modal属性中设置  modal:{title:'标题',with: 1000}

**Comment by holiy930561** [comment]
thanks
