### ISSUE TITLE
启动后，控制台一片红,希望作者能直接修改npm包，react高版本报错，先谢谢了

### ISSUE THREAD

**Issue by changchengyan** [sxfad/react-admin#65]
npm 核心依赖 书写格式有问题 
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `HeaderUser`. See https://fb.me/react-warning-keys for more information.
    in Divider (created by HeaderUser)
```

`index.js:1 Warning: React does not recognize the `otherHeight` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `otherheight` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

**Comment by zkboys** [comment]
已解决，可以升级一下 ra-lib 库，yarn remove ra-lib && yarn add ra-lib
