### ISSUE TITLE
你好，请问支持配置hash路由吗？

### ISSUE THREAD

**Issue by BiggerHacker** [sxfad/react-admin#66]
我把router/AppRouter.jsx的BrowserRouter 修改为HashRouter之后，页面会出现很多的问题。

菜单无法匹配路由进行selected选中。

退出登录，左侧会出现body padding-left的菜单空白区块。

以及其他的一些小问题。

**Comment by zkboys** [comment]
暂时不支持 HashRouter

**Comment by BiggerHacker** [comment]
> 暂时不支持 HashRouter

好的，谢谢。
