### ISSUE TITLE
ra-lib包更新后,所有的弹窗，不管大小，统一点击不了，而且很卡

### ISSUE THREAD

**Issue by changchengyan** [sxfad/react-admin#68]
所有的弹窗能加出来，但是关闭不了，能不能做一下测试回归，这个问题很严重

**Comment by zkboys** [comment]
我这无法复现问题，把你出问题的代码贴一下，我看看。

**Comment by changchengyan** [comment]
我刚把最新的主仓库的前端 代码拉取下来 再次原封不动的测试了一次，比如列表页的 点击删除按钮出现的确认弹窗能打开，但是关闭不了，账户名称的下拉窗口能展开 但是关不了，配置弹窗也是一样，其他也类似
确实有点疑惑，点击关闭的窗口图标全部无效，即使点击保存 侧边弹窗显示成功 页无法关闭窗口；

环境  node  12.8  cnpm 6.1.1   使用 cnpm下载的依赖 、win10 64位，七八天前的还是可以直接执行的

**Comment by changchengyan** [comment]
I find reason, just  because  npm install the packages , I  use  yarn ,  all done!!!!  Any way ,Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
