### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by 1422667480** [sxfad/react-admin#69]
用 yarn install   或者   yarn --registry=https://registry.npm.taobao.org 或者直接 cnpm install   都会报错  "https://registry.npm.taobao.org/@babel/plugin-transform-react-constant-elements/-/plugin-transform-react-constant-elements-7.9.0.tgz: Request failed \"404 Not Found\"".

**Comment by zkboys** [comment]
把  yarn.lock 中https://registry.npm.taobao.org 全部替换成 https://registry.npmjs.org 安装试试。

**Comment by zkboys** [comment]
不行把 yarn.lock 删除，之后再安装试试。估计是 淘宝镜像上文件丢失。

**Comment by 1422667480** [comment]
yarn.lock 里 替换也没用 只有在install 的时候 https://registry.npmjs.org  才行 就是 太。。。。。慢了

**Comment by zkboys** [comment]
把 yarn.lock 文件删掉，然后 yarn --registry https://registry.npm.taobao.org 进行安装，安装过程中会报一些提醒，但是也没关系。
