### ISSUE TITLE
布局方式的文件缺失

### ISSUE THREAD

**Issue by FrontEndZhang** [sxfad/react-admin#70]
官网上说导航布局可以通过修改src/models/settings.js来指定布局方式
但是这个文件夹里面没有这个文件

**Comment by zkboys** [comment]
框架最近有跟新，抱歉，文档没有来的及跟新，后续不忙了会修改，目前可以再src/models/index.js中修改默认值：`pageFrameLayout: PAGE_FRAME_LAYOUT.TOP_SIDE_MENU,`
