### ISSUE TITLE
你好，请问默认首页导航的路由可以修改吗？

### ISSUE THREAD

**Issue by BiggerHacker** [sxfad/react-admin#71]
1. 目前默认首页的路由，是没有在菜单上显示的，请问可以修改默认首页的导航为某一个菜单项么？

2. 目前判断未登录是根据localstroage的LOGIN_USER_STORAGE_KEY来判断，请问这个可以去掉不？我想直接根据axios的接口请求情况来拦截。

**Comment by zkboys** [comment]
1. 可以吧其他页面的path 改成 '/'，home页面改成 其他，比如 '/home'
2. 框架中 src/commons/handle-error.js中有对未登录进行处理，默认是后端返回401，直接跳转登录页面，localStorage中存的user只是前端判断是否登录使用，并不准确，如果不需要，可以再 src/router/AuthRoute.jsx中修改，把拦截去掉 `if (!noAuth && !isLogin()) return toLogin();`

**Comment by BiggerHacker** [comment]
第二个好像不行，我在src/router/AuthRoute.jsx中去掉拦截，退出登陆之后，还是进不去页面，会自动跳转到登陆页。

**Comment by BiggerHacker** [comment]
我在src/router/AppRouter.jsx中尝试去掉`if (!isLogin()) return null;`也不行。

**Comment by BiggerHacker** [comment]
我把所有的isLogin拦截都去掉，没问题了现在。谢谢大佬
