### ISSUE TITLE
大佬，右侧内容区 列表数量展示超过十个，点击LOGO旁边的按钮，对菜单收起展开或者拖拽大小，就会开始卡顿了。

### ISSUE THREAD

**Issue by BiggerHacker** [sxfad/react-admin#77]
如果列表数量 每页二十条，左侧菜单会变得非常非常卡。

移动端模拟器很顺滑，实机没测试，但是pc上很卡顿。

**Comment by zkboys** [comment]
测试了一下，Table 组件如果是用了scroll 属性就会很卡，ra-lib 中 table使用了scroll 用于沾满全屏~，暂时没想到啥好办法，可以将菜单收起动画去掉，菜单拖拽改变大小功能去掉。

**Comment by BiggerHacker** [comment]
> 测试了一下，Table 组件如果是用了scroll 属性就会很卡，ra-lib 中 table使用了scroll 用于沾满全屏~，暂时没想到啥好办法，可以将菜单收起动画去掉，菜单拖拽改变大小功能去掉。

之前测试还发现，如果列表出现横向滚动条，并且菜单收起之后 横向滚动条还存在的情况下，菜单动画很流畅

如果table没有横向滚动，就卡顿了。

**Comment by BiggerHacker** [comment]
> 测试了一下，Table 组件如果是用了scroll 属性就会很卡，ra-lib 中 table使用了scroll 用于沾满全屏~，暂时没想到啥好办法，可以将菜单收起动画去掉，菜单拖拽改变大小功能去掉。

还有请问怎么去掉菜单收起动画和拖拽功能。

**Comment by zkboys** [comment]
找到相应元素 通过 样式覆盖 transition: none即可。拖拽条通过 display:none隐藏掉。
