### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by GongYanfu** [sxfad/react-admin#85]
项目成功跑起来，但是登录有问题，求大佬联系方式，或者加一下我QQ：1534784540

**Comment by zkboys** [comment]
公司的后端代码无法提供，短时间内整理了一下mock数据，可以作为后端开发参考，相关sql及接口mock代码在src/mock目录下。
获取最新代码，通过REACT_APP_MOCK=true yarn start 启动。请求会走mock数据。
