### ISSUE TITLE
您好，打包后找不到login页！

### ISSUE THREAD

**Issue by goudanz** [sxfad/react-admin#87]
您好，问题是这样的：

服务器是java，springboot做的，我是执行yarn build 后，把build目录的文件放在java程序的public下。

然后对整个java打包，启动后就无法找到login页，

翻看了之前历史的issues #23 ，除过大佬 @zkboys 在里面描述的将404重定向到idnex之外，还有有更好的解决方案嘛？

**Comment by zkboys** [comment]
没有什么特别的方法，前后端分离之后，路由是前端管理了，所有的页面请求后端直接指向首页，由前端进行页面跳转。可以网上找一下java,springboot如何配置。

**Comment by goudanz** [comment]
> 没有什么特别的方法，前后端分离之后，路由是前端管理了，所有的页面请求后端直接指向首页，由前端进行页面跳转。可以网上找一下java,springboot如何配置。

好的，麻烦您了～
