### ISSUE TITLE
麻烦问下v5版本样式文件恢复成原始结构的方法，不需要命令antd:less

### ISSUE THREAD

**Issue by goudanz** [sxfad/react-admin#93]
引用下 #89 的issues；

现在发现一些样式因为受到public/antd.min.css文件的影响，导致一些组件的样式被冲突覆盖，导致无法使用。

想咨询下，怎么才能恢复原始状态，像这里说的：https://github.com/sxfad/react-admin/issues/89#issuecomment-888031497

其实我们也不用提高打包速度啥的。。

请问可以恢复嘛？就像现在master版本的样式一样。

**Comment by zkboys** [comment]
配置文件都在项目中，可以自己尝试修改一下。
