### ISSUE TITLE
最近更新谷歌版本到91后发现所有列表高度直接适应整个页面了，拉到老长，在其他浏览器又不存在这个问题，有木有好的解决方案

### ISSUE THREAD

**Issue by Roylb** [sxfad/react-admin#94]
![image](https://user-images.githubusercontent.com/20588038/129013887-d0e33ab0-4cb0-4785-a920-d9289f8e5907.png)

**Comment by zkboys** [comment]
如果使用的是ra-lib ，升级ra-lib 到最新版本：`"ra-lib": "^1.3.7",`，相关命令：`yarn add ra-lib`

如果是使用的项目中`src/library`库，修改如下：
文件：`src/library/components/table/index.jsx`
删除：79行：`this.tableTBody = this.wrapper.querySelector('.ant-table-tbody');`
删除：111行：`this.tableTBody.style.height = `${tableBodyHeight}px`;`
![image](https://user-images.githubusercontent.com/11864780/129016571-e5ea1e40-8dfd-4d6b-8ba1-594c36b41a86.png)

**Comment by Roylb** [comment]
谢谢大佬
