### ISSUE TITLE
麻烦问下QueryBar是否支持像antdPro里的QueryFilter的高级搜索功能？

### ISSUE THREAD

**Issue by goudanz** [sxfad/react-admin#96]
有个列表的搜索条件有点多。想弄个类似这个的展开折叠。。现有的queryBar支持这个嘛？还是要我手动实现呢？

https://procomponents.ant.design/components/query-filter

![image](https://user-images.githubusercontent.com/23636449/129332956-f56b4b2e-83ac-4430-876c-90ce3fbe6472.png)

![image](https://user-images.githubusercontent.com/23636449/129332975-e8918c63-e2c1-46ae-9789-231b320fd2dd.png)

**Comment by zkboys** [comment]
支持，通过 render props 方式
![image](https://user-images.githubusercontent.com/11864780/129333754-2cacd713-dd73-4cfe-9be8-5fe61a5b0d78.png)
![image](https://user-images.githubusercontent.com/11864780/129333758-688d8ff9-6da2-433d-955d-e9fbef0faf50.png)

**Comment by zkboys** [comment]
支持，相关API：
![image](https://user-images.githubusercontent.com/11864780/129334263-fb381be1-76e5-496c-be82-00fc56221d51.png)

**Comment by goudanz** [comment]
大佬。你们的ralib文档有点不全呀。。。

要是全点。我们这能全使用您这套脚手架。。。嘿嘿

**Comment by goudanz** [comment]
> 支持，相关API：
> ![image](https://user-images.githubusercontent.com/11864780/129334263-fb381be1-76e5-496c-be82-00fc56221d51.png)

这个文档有具体的地址嘛？

**Comment by goudanz** [comment]
我用的是v5分支的代码呀。

这是版本："ra-lib": "^1.3.2",

这个也支持的嘛？加了 <QueryBar showCollapsed={true}></QueryBar> 貌似没显示

**Comment by goudanz** [comment]
![image](https://user-images.githubusercontent.com/23636449/129339586-5c8c30fa-4093-4709-8a1e-f491ffbd60fa.png)

 显示了！

**Comment by goudanz** [comment]
按钮是出来了。但是点击没变化。所以我要在onCollapsedChange事件里写 隐藏的代码 是嘛？

**Comment by goudanz** [comment]
我看了index.esm.js里的代码，发现了：

```
FormElement.propTypes = {
...
...
hidden: PropTypes.any,
}
```

有这个hidden属性的，。但是为啥在我的业务代码中不生效？
```
<FormElement
                            {...formProps}
                            type="select"
                            mode="multiple"
                            hidden={!collapsed}
                            label="列表"
                            maxTagCount={1}
                            name="list"
                            options={list}
                        />
```

**Comment by goudanz** [comment]
> 我看了index.esm.js里的代码，发现了：
> 
> ```
> FormElement.propTypes = {
> ...
> hidden: PropTypes.any,
> }
> ```
> 
> 创建FormElement时是有这个hidden属性的，但是为啥在我的业务代码中不生效？
> 
> 这是我的部分代码：
> 
> ```
> const [collapsed, setCollapsed] = useState(false);
> 
> async function doCollapsed() {
>     setCollapsed(! collapsed);
> }
> 
> <QueryBar collapsed={collapsed} onCollapsedChange={doCollapsed}>
>       <FormElement
>             {...formProps}
>             type="select"
>             mode="multiple"
>             hidden={!collapsed}
>             label="列表"
>             maxTagCount={1}
>             name="list"
>             options={list}
>         />
> </QueryBar>
> ```

我只有改成这样：
```
{collapsed ?  <FormElement
            {...formProps}
            type="select"
            mode="multiple"
            hidden={!collapsed}
            label="列表"
            maxTagCount={1}
            name="list"
            options={list}
/>: null}
```

才能生效；是需要我这样做嘛？

**Comment by zkboys** [comment]
使用 `import {FormItem} from 'ra-lib';`，不要使用FormElement，FormElement是做老版本兼容使用的，已经启用了。

**Comment by goudanz** [comment]
> 使用 `import {FormItem} from 'ra-lib';`，不要使用FormElement，FormElement是做老版本兼容使用的，已经弃用了。

好的

**Comment by goudanz** [comment]
> 使用 `import {FormItem} from 'ra-lib';`，不要使用FormElement，FormElement是做老版本兼容使用的，已经弃用了。

v5版本里使用FormItem 整个表单的样式会错乱。。。

**Comment by goudanz** [comment]
然后我自己写了样式控制：

```
    const layout = {
        labelCol: {
            span: 7
        },
        wrapperCol: {
            span: 16
        }
    };

 <Form
                {...layout}
/>
```

虽然部分对齐了。但其他的各种组件更乱了。

**Comment by zkboys** [comment]
那就继续使用 FormElement， 可以使用div控制显示隐藏，不要用三元判断，否则form表单会丢失隐藏元素的数据。
```jsx
<div style={{display: collapsed ? 'none' : 'block'}}>
FormElement1
FormElement2
FormElement3
</div>
```

**Comment by goudanz** [comment]
> 那就继续使用 FormElement， 可以使用div控制显示隐藏，不要用三元判断，否则form表单会丢失隐藏元素的数据。
> 
> ```js
> <div style={{display: collapsed ? 'none' : 'block'}}>
> FormElement1
> FormElement2
> FormElement3
> </div>
> ```

我把
```
 const layout = {
        labelCol: {
            span: 7
        },
        wrapperCol: {
            span: 16
        }
    };
```
改成
```
    const layout = {
        labelCol: {flex: '100px'},
    };
```

没有太乱了

**Comment by goudanz** [comment]
我把master版本里：https://github.com/sxfad/react-admin/blob/master/src/pages/menus/MenuEdit.jsx 的布局代码搬过来了。

**Comment by goudanz** [comment]
谢谢您！ 麻烦您啦
