### ISSUE TITLE
在组件里使用className时，不生效

### ISSUE THREAD

**Issue by goudanz** [sxfad/react-admin#98]
比如，我使用：

```
<Button className="test">数据恢复</Button>
```

style.less中：
```
.test{
    background-color: red;
}
```
显示:

![image](https://user-images.githubusercontent.com/23636449/129711744-c0a893d4-c06b-45a8-81ec-2a6c8e5cff7c.png)

![image](https://user-images.githubusercontent.com/23636449/129711807-b62cf2e6-fce1-4f4b-925c-42b7225b9ad5.png)

它已经有了这个class了，但还是不生效！ 请问这种问题该怎么处理？

这个问题是否是因为 #93 说的那样导致的呢？

然后我在button组件里写style，就能生效；

```
<Button style={{backgroundColor:'red'}} >数据恢复</Button>,
```
![image](https://user-images.githubusercontent.com/23636449/129712211-13900fda-2abc-4aeb-ad61-400ea4026ecf.png)

**Comment by zkboys** [comment]
项目中使用了css module ，几种方式
1. 使用 styleName 代替 className
```
import './style.less'

<Button styleName="test">按钮</Button>
```
2. 使用styles变量
```
import styles from './style.less';
<Button className={styles.test}>按钮</Button>
```

**Comment by goudanz** [comment]
> styleName

这个没问题了。不好意思。我才想起来文档中有这么说过的。我没仔细看。
